using System.Text;
using System.Text.RegularExpressions;
using GitCheckoutManager.Models;

namespace GitCheckoutManager.Services
{
    /// <summary>Why the last action left a submodule alone on purpose (as opposed to failing).</summary>
    public enum SubmoduleSkipReason
    {
        None, UncommittedChanges, Declined,
        /// <summary>Pull: HEAD is detached, so there is no branch to fast-forward.</summary>
        NotOnBranch,
        /// <summary>The branch does not exist on the submodule's own origin.</summary>
        BranchNotOnRemote,
        /// <summary>The local branch has commits that aren't on origin, so it was left as it is.</summary>
        LocalCommits,
        /// <summary>The submodule is gone, not populated any more, or has nothing left to do.</summary>
        NotAvailable
    }

    /// <summary>One submodule with the error its last action left, if any, and whether that was a deliberate skip.</summary>
    public sealed record SubmoduleReportItem(SubmoduleInfo Info, string? Error, SubmoduleSkipReason Skip = SubmoduleSkipReason.None)
    {
        /// <summary>A real failure: there is an error and the row was not merely skipped.</summary>
        public bool IsFailure => !string.IsNullOrWhiteSpace(Error) && Skip == SubmoduleSkipReason.None;
    }

    /// <summary>Formats the plain-text report a user can paste to the maintainer of a repository with broken submodules.</summary>
    public static class SubmoduleReportBuilder
    {
        // "https://user:token@host/…" → "https://host/…"
        private static readonly Regex UserInfo = new(@"(?<=://)[^/@\s]*@", RegexOptions.Compiled);

        // "Authorization: Basic …", "PRIVATE-TOKEN: …": the value runs to the end of the line or the next quote.
        // A bare "token:" is left alone so a message like "invalid token: bad credentials" stays readable.
        private static readonly Regex HeaderSecret = new(
            @"(?i)\b(authorization|private-token|job-token|(?:access|oauth|private)[_-]token)\b\s*:\s*[^\r\n'""]+",
            RegexOptions.Compiled);

        // "private_token=…", "?access_token=…", any key containing "token": covers URL query strings too.
        private static readonly Regex KeyValueSecret = new(
            @"(?i)\b([\w-]*token[\w-]*)\s*=\s*[^\s&#'""]+",
            RegexOptions.Compiled);

        /// <summary>True when the row belongs in a report: missing from .gitmodules, not initialized, failed, URL overridden, or cloned manually.</summary>
        public static bool IsReportable(SubmoduleReportItem item) =>
            item.Info.State is SubmoduleState.MissingFromGitmodules or SubmoduleState.ManuallyCloned
                or SubmoduleState.NotInitialized ||
            item.Info.UrlOverridden ||
            item.IsFailure ||
            item.Skip == SubmoduleSkipReason.UncommittedChanges;

        public static string Build(string? remoteUrl, string? branch, string? headSha, string version,
            DateTime date, IEnumerable<SubmoduleReportItem> items)
        {
            var list = items.ToList();
            var sb = new StringBuilder();

            sb.Append("Submodule report — ").Append(string.IsNullOrWhiteSpace(remoteUrl) ? "unknown repository" : Clean(remoteUrl));
            if (!string.IsNullOrWhiteSpace(branch)) sb.Append(" @ ").Append(branch);
            if (!string.IsNullOrWhiteSpace(headSha)) sb.Append(" (").Append(Short(headSha)).Append(')');
            sb.AppendLine();
            sb.AppendLine($"Generated by Git Checkout Manager {version} on {date:yyyy-MM-dd}");

            Section(sb, "Missing from .gitmodules (needs a .gitmodules entry in the repository):",
                list.Where(i => i.Info.State == SubmoduleState.MissingFromGitmodules)
                    .Select(i => new[] { $"{i.Info.DisplayPath} — pinned {Short(i.Info.PinnedSha)}" }));

            Section(sb, "Failed to initialize:",
                list.Where(i => i.IsFailure)
                    .Select(i =>
                    {
                        var head = string.IsNullOrWhiteSpace(i.Info.Url)
                            ? i.Info.DisplayPath
                            : $"{i.Info.DisplayPath} — url {Clean(i.Info.Url)}";
                        return new[] { head, "  " + FirstErrorLine(i.Error!) };
                    }));

            Section(sb, "Skipped (uncommitted changes):",
                list.Where(i => i.Skip == SubmoduleSkipReason.UncommittedChanges)
                    .Select(i => new[] { i.Info.DisplayPath }));

            // No error text: typically failed during the clone script, whose output this window never saw.
            Section(sb, "Not initialized (may have failed during clone; run Initialize selected to see the error):",
                list.Where(i => i.Info.State == SubmoduleState.NotInitialized && string.IsNullOrWhiteSpace(i.Error) && i.Skip == SubmoduleSkipReason.None)
                    .Select(i => new[]
                    {
                        string.IsNullOrWhiteSpace(i.Info.Url)
                            ? i.Info.DisplayPath
                            : $"{i.Info.DisplayPath} — url {Clean(i.Info.Url)}"
                    }));

            Section(sb, "Fixed locally in this checkout (the repository still needs fixing):",
                list.Where(i => i.Info.UrlOverridden || i.Info.State == SubmoduleState.ManuallyCloned)
                    .Select(i => new[] { FixedLine(i.Info) }));

            return sb.ToString();
        }

        private static string FixedLine(SubmoduleInfo info) =>
            info.State == SubmoduleState.ManuallyCloned
                ? $"{info.DisplayPath} — cloned manually from {Clean(info.EffectiveUrl)}"
                : $"{info.DisplayPath} — .gitmodules says {Clean(info.Url)}, using {Clean(info.EffectiveUrl)}";

        /// <summary>Writes a titled block; each entry is its first line behind "- " plus optional continuation lines.</summary>
        private static void Section(StringBuilder sb, string title, IEnumerable<string[]> entries)
        {
            var list = entries.ToList();
            if (list.Count == 0) return;

            sb.AppendLine().AppendLine(title);
            foreach (var entry in list)
            {
                sb.Append("  - ").AppendLine(entry[0]);
                foreach (var extra in entry.Skip(1)) sb.Append("    ").AppendLine(extra.TrimStart());
            }
        }

        /// <summary>The first "fatal:" or "error:" line of git's output, else its first non-empty line.</summary>
        public static string FirstErrorLine(string error)
        {
            var lines = error.Split('\n').Select(l => l.Trim()).Where(l => l.Length > 0).ToList();
            var line = lines.FirstOrDefault(l =>
                    l.StartsWith("fatal:", StringComparison.OrdinalIgnoreCase) ||
                    l.StartsWith("error:", StringComparison.OrdinalIgnoreCase))
                ?? lines.FirstOrDefault() ?? string.Empty;
            return Clean(line);
        }

        /// <summary>Removes credentials from a URL or message: user info in URLs, token query parameters and token/authorization values.</summary>
        private static string Clean(string? text)
        {
            if (text == null) return string.Empty;
            var cleaned = UserInfo.Replace(text, string.Empty);
            cleaned = HeaderSecret.Replace(cleaned, "$1: [removed]");
            return KeyValueSecret.Replace(cleaned, "$1=[removed]");
        }

        private static string Short(string sha) => sha.Length > 8 ? sha[..8] : sha;
    }
}
