using GitCheckoutManager.Models;
using GitCheckoutManager.Services;

namespace GitCheckoutManager.Tests;

public class SubmoduleReportBuilderTests
{
    private const string Sha = "b93f3590aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    private static readonly DateTime Day = new(2026, 10, 3);

    private static SubmoduleInfo Sub(string path, SubmoduleState state, string? url = null, bool overridden = false,
        string? effective = null, string? display = null) =>
        new(path, path, url, null, Sha, null, state, overridden, effective, "C:\\repo", display ?? path, 0);

    private static string Build(params SubmoduleReportItem[] items) =>
        SubmoduleReportBuilder.Build("https://example.com/group/repo.git", "main", "1234567890abcdef", "1.2.3", Day, items);

    [Fact]
    public void Header_names_repository_branch_short_sha_version_and_date()
    {
        var text = Build(new SubmoduleReportItem(Sub("a", SubmoduleState.MissingFromGitmodules), null));

        Assert.StartsWith("Submodule report — https://example.com/group/repo.git @ main (12345678)", text);
        Assert.Contains("Generated by Git Checkout Manager 1.2.3 on 2026-10-03", text);
    }

    [Fact]
    public void Sections_appear_only_when_they_have_entries()
    {
        var text = Build(new SubmoduleReportItem(Sub("external/broken-missing", SubmoduleState.MissingFromGitmodules), null));

        Assert.Contains("Missing from .gitmodules", text);
        Assert.Contains("  - external/broken-missing — pinned b93f3590", text);
        Assert.DoesNotContain("Failed to initialize", text);
        Assert.DoesNotContain("Fixed locally", text);
    }

    [Fact]
    public void Failed_entry_shows_url_and_first_fatal_or_error_line_only()
    {
        var error = "Cloning into 'x'...\nfatal: repository 'https://example.com/gone.git/' not found\nfatal: clone of 'x' failed\nFailed to clone";
        var text = Build(new SubmoduleReportItem(
            Sub("external/broken-url", SubmoduleState.NotInitialized, "../gone.git"), error));

        Assert.Contains("Failed to initialize:", text);
        Assert.Contains("  - external/broken-url — url ../gone.git", text);
        Assert.Contains("    fatal: repository 'https://example.com/gone.git/' not found", text);
        Assert.DoesNotContain("Cloning into", text);
        Assert.DoesNotContain("clone of 'x' failed", text);
        Assert.DoesNotContain("Missing from .gitmodules", text);
    }

    [Fact]
    public void Not_initialized_rows_without_an_error_get_their_own_section_after_Failed()
    {
        var text = Build(
            new SubmoduleReportItem(Sub("external/failed", SubmoduleState.NotInitialized, "../a.git"), "fatal: nope"),
            new SubmoduleReportItem(Sub("external/broken-url", SubmoduleState.NotInitialized, "../gsm-test-does-not-exist.git"), null));

        const string title = "Not initialized (may have failed during clone; run Initialize selected to see the error):";
        Assert.Contains(title + Environment.NewLine + "  - external/broken-url — url ../gsm-test-does-not-exist.git", text);
        Assert.True(text.IndexOf("Failed to initialize:", StringComparison.Ordinal) < text.IndexOf(title, StringComparison.Ordinal));

        // A row that already has an error appears under Failed only.
        Assert.Equal(1, text.Split("external/failed").Length - 1);
        Assert.DoesNotContain("Missing from .gitmodules", text);
    }

    [Fact]
    public void Fixed_locally_lists_overridden_urls_and_manual_clones()
    {
        var text = Build(
            new SubmoduleReportItem(Sub("external/broken-url", SubmoduleState.Ready, "../gone.git", true,
                "https://example.com/lib.git"), null),
            new SubmoduleReportItem(Sub("external/broken-missing", SubmoduleState.ManuallyCloned, null, false,
                "https://example.com/lib.git"), null));

        Assert.Contains("Fixed locally in this checkout (the repository still needs fixing):", text);
        Assert.Contains("  - external/broken-url — .gitmodules says ../gone.git, using https://example.com/lib.git", text);
        Assert.Contains("  - external/broken-missing — cloned manually from https://example.com/lib.git", text);
        Assert.DoesNotContain("Failed to initialize", text);
        Assert.DoesNotContain("Missing from .gitmodules", text);
    }

    [Fact]
    public void Nested_rows_are_reported_by_their_display_path()
    {
        var text = Build(new SubmoduleReportItem(
            Sub("vendor/x", SubmoduleState.MissingFromGitmodules, display: "external/lib/vendor/x"), null));

        Assert.Contains("  - external/lib/vendor/x — pinned b93f3590", text);
    }

    [Fact]
    public void Credentials_never_reach_the_report()
    {
        const string secret = "glpat-SECRET123";
        var text = SubmoduleReportBuilder.Build(
            $"https://oauth2:{secret}@example.com/group/repo.git", "main", Sha, "1.0", Day,
            new[]
            {
                new SubmoduleReportItem(
                    Sub("a", SubmoduleState.NotInitialized, $"https://user:{secret}@example.com/a.git"),
                    $"fatal: unable to access 'https://user:{secret}@example.com/a.git/': denied\nAuthorization: Basic {secret}"),
                new SubmoduleReportItem(
                    Sub("b", SubmoduleState.Ready, "../b.git", true, $"https://oauth2:{secret}@example.com/b.git"), null),
                new SubmoduleReportItem(
                    Sub("c", SubmoduleState.NotInitialized, "../c.git"), $"error: PRIVATE-TOKEN: {secret}")
            });

        Assert.DoesNotContain("SECRET", text);
        Assert.DoesNotContain("oauth2", text);
        Assert.Contains("https://example.com/group/repo.git", text);
        Assert.Contains("using https://example.com/b.git", text);
    }

    private static string Failed(string url, string? error) =>
        Build(new SubmoduleReportItem(Sub("a", SubmoduleState.NotInitialized, url), error));

    [Theory]
    [InlineData("https://h/x.git?private_token=glpat-abc")]
    [InlineData("https://h/x.git?access_token=glpat-abc")]
    [InlineData("https://h/x.git?ref=main&oauth_token=glpat-abc&x=1")]
    [InlineData("https://h/x.git?mytoken=glpat-abc")]
    public void Token_query_parameters_are_removed_from_urls(string url)
    {
        var text = Failed(url, "fatal: nope");

        Assert.DoesNotContain("glpat", text);
        Assert.Contains("token=[removed]", text);
    }

    [Fact]
    public void Query_parameters_next_to_a_removed_token_are_kept()
    {
        var text = Failed("https://h/x.git?ref=main&private_token=glpat-abc&x=1", null);

        Assert.Contains("https://h/x.git?ref=main&private_token=[removed]&x=1", text);
    }

    [Fact]
    public void Token_in_a_url_inside_an_error_message_is_removed()
    {
        var text = Failed("../a.git",
            "fatal: unable to access 'https://h/x.git/?private_token=glpat-abc': denied");

        Assert.DoesNotContain("glpat", text);
        Assert.Contains("denied", text);
    }

    [Fact]
    public void Authentication_failed_message_with_user_info_is_cleaned()
    {
        var text = Failed("../a.git", "fatal: Authentication failed for 'https://oauth2:glpat-abc@h/x.git'");

        Assert.DoesNotContain("glpat", text);
        Assert.DoesNotContain("oauth2", text);
        Assert.Contains("fatal: Authentication failed for 'https://h/x.git'", text);
    }

    [Fact]
    public void An_ordinary_message_that_mentions_a_token_is_kept()
    {
        var text = Failed("../a.git", "fatal: invalid token: bad credentials");

        Assert.Contains("invalid token: bad credentials", text);
    }

    [Fact]
    public void Header_values_stop_at_the_end_of_the_line_or_the_next_quote()
    {
        var text = Failed("../a.git", "fatal: sent 'PRIVATE-TOKEN: glpat-abc' but the server said no");
        Assert.DoesNotContain("glpat", text);
        Assert.Contains("PRIVATE-TOKEN: [removed]' but the server said no", text);

        var line = SubmoduleReportBuilder.FirstErrorLine("error: Authorization: Basic glpat-abc");
        Assert.Equal("error: Authorization: [removed]", line);
    }

    [Fact]
    public void IsReportable_matches_the_four_problem_kinds_only()
    {
        bool R(SubmoduleInfo i, string? error = null) => SubmoduleReportBuilder.IsReportable(new(i, error));

        Assert.True(R(Sub("a", SubmoduleState.MissingFromGitmodules)));
        Assert.True(R(Sub("a", SubmoduleState.ManuallyCloned)));
        Assert.True(R(Sub("a", SubmoduleState.Ready, overridden: true)));
        Assert.True(R(Sub("a", SubmoduleState.NotInitialized), "fatal: x"));

        Assert.False(R(Sub("a", SubmoduleState.Ready)));
        Assert.True(R(Sub("a", SubmoduleState.NotInitialized)));
        Assert.False(R(Sub("a", SubmoduleState.DifferentCommit)));
    }
}
